### ISSUE TITLE
Feedback wanted: Getting notified about set starts/successes

### ISSUE THREAD

**Issue by PixievoltNo1** [PixievoltNo1/svelte-webext-storage-adapter#1]
Currently, consumers of this package have no way to be notified when one of its `StorageArea.set()` calls starts or succeeds, only when it fails (that's the [`onSetError` option](https://github.com/PikadudeNo1/svelte-webext-storage-adapter/blob/master/README.md#onseterror)). This is sufficient for my use cases, as I make single-page-app WebExtensions that save small amounts of data at a time - but I'd love for my work to help as many people as it can. So, I'd like for the people who would be helped to tell me about their use cases and what changes they'd like to see.

The simplest thing to do would be to change the `onSetError` option to an `onSet` option that takes a Promise representing the set in progress. I could also return such a promise from a store's `set`/`update` call, but you can't get a return value from setting an `$autoSubscription`.

**Comment by SDreuW6** [comment]
bug

**Comment by PixievoltNo1** [comment]
I see this good some upvotes. I've proposed an API as part of #14; check it out and make sure it works for your needs.

**Comment by PixievoltNo1** [comment]
I'm closing this as it is now part of the v3 beta and is not at risk of removal. Leave your feedback for `onWrite` on #14.
