### ISSUE TITLE
webextension-polyfill support

### ISSUE THREAD

**Issue by dhysuiej** [PixievoltNo1/svelte-webext-storage-adapter#9]
Has anyone managed to use this package with [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) ?

**Comment by PixievoltNo1** [comment]
This package doesn't use the `browser.*` API provided by the polyfill, but rather the `chrome.*` API natively provided by Chrome and all WebExtension-compliant browsers. It won't matter whether you use the polyfill or not.

**Comment by dhysuiej** [comment]
Thanks for the quick reply.

BTW, any idea why the store might not work on firefox?

I have an options page that stores some data that is read from the popup page, and it works fine on Chrome but not Firefox.

After reading about the option `storageArea` I thought maybe passing `browser.storage.sync` would do the trick, if there were some logic detecting what kind of storage is being used, and would also make the store work on Safari.
